info:
  # Site title
  title: Kazuma Shugen
  # Site subtitle
  subtitle: Media about anime and manga for otaku from all over the world!
  # Author name
  author: Kazuma Shugen
  # Site URL
  url: https://kazumashugen.vercel.app
# BASIC INFORMATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# IMAGE CONFIGURATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
defaults:
  # Favicon
  favicon: /images/favicon.svg
  # Site logo
  logo: 
  # Site avatar
  avatar: /images/avatar-0.jpg
# IMAGE CONFIGURATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# COLORS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
colors:
  #Primary color
  primary: "#A31F34"
  # Secondary color
  secondary:
  # Default theme mode
  default_mode: dark # light, dark
# COLORS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# SITE CUSTOMIZATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
global:
  fonts:
    chinese: 
      enable: false
    english: 
      enable: true
      family: "'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif"
      url: "https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap"
    title:
      enable: true
      family: "'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif"
      url: "https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap"
  content_max_width: 1000px
  sidebar_width: 210px
  hover:
    shadow: true
    scale: false
  scroll_progress:
    bar: false
    percentage: true
  website_counter:
    url: https://cn.vercount.one/js
    enable: true
    site_pv: true
    site_uv: true
    post_pv: true
  single_page: true
  preloader:
    enable: true
    custom_message: "Kazuma Shugen"
  open_graph:
    enable: true
    image: /images/og.webp
    description: Media about anime and manga for otaku from all over the world!
  google_analytics:
    enable: false
    id:
# SITE CUSTOMIZATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# FONTAWESOME >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
fontawesome:
  thin: false
  light: false
  duotone: false
  sharp_solid: false
# FONTAWESOME <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# HOME BANNER >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
home_banner:
  enable: true
  style: fixed
  image: 
    light: /assets/banner.png
    dark: /assets/banner.png
  title: Kazuma Shugen
  subtitle:
    text: ['Media about anime and manga for otaku from all over the world!', 'Anime • Manga • Light Novels']
    hitokoto:
      enable: false
      show_author: true
      api: https://v1.hitokoto.cn
    typing_speed: 80
    backing_speed: 60
    starting_delay: 500
    backing_delay: 2000
    loop: true
    smart_backspace: true
  text_color: 
    light: "#fff"
    dark: "#d1d1b6"
  text_style: 
    title_size: 2.8rem
    subtitle_size: 1.5rem
    line_height: 1.2
  custom_font: 
    enable: false
  social_links:
    enable: false
# HOME BANNER <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# NAVIGATION BAR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
navbar:
  auto_hide: true
  color:
    left: "#A31F34"
    right: "#1a1a2e"
    transparency: 50
  width:
    home: 1200px
    pages: 1000px
  links:
    Home: 
      path: / 
      icon: fa-regular fa-house
    Anime:
      path: /tags/Anime
      icon: fa-solid fa-tv
    Manga:
      path: /tags/Manga
      icon: fa-solid fa-book-open
    Light Novels:
      path: /tags/Light-Novels
      icon: fa-solid fa-feather
    Album: 
      icon: fa-solid fa-image
      path: /masonry/
    Archives: 
      path: /archives 
      icon: fa-regular fa-archive
    About: 
      path: /about
      icon: fa-solid fa-circle-info
  search:
    enable: false
    preload: true
# NAVIGATION BAR <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# HOME PAGE ARTICLE SETTINGS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
home:
  sidebar:
    enable: true
    position: left
    first_item: menu
    announcement:
    show_on_mobile: true
    links:
      Archives: 
        path: /archives 
        icon: fa-regular fa-archive
  article_date_format: auto
  excerpt_length: 200
  categories:
    enable: false
    limit: 3
  tags:
    enable: true
    limit: 3
# HOME PAGE ARTICLE SETTINGS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# ARTICLE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
articles:
  style:
    font_size: 16px
    line_height: 1.6
    image_border_radius: 14px
    image_alignment: center
    image_caption: false
    link_icon: true
    delete_mask: false
    title_alignment: left
    headings_top_spacing:
      h1: 3.2rem
      h2: 2.4rem
      h3: 1.9rem
      h4: 1.6rem
      h5: 1.4rem
      h6: 1.3rem
  word_count:
    enable: true
    count: true
    min2read: true
  author_label: 
    enable: false
    auto: false
    list: []
  code_block:
    copy: true
    style: mac
    highlight_theme:
      light: github
      dark: vs2015
    font:
      enable: false
  toc:
    enable: true
    max_depth: 3
    number: false
    expand: true
    init_open: true
  copyright:
    enable: true
    default: cc_by_nc_sa
  lazyload: true
  pangu_js: false
  recommendation:
    enable: false
    title: Recommended Reading
    limit: 3
    mobile_limit: 2
    placeholder: /images/wallhaven-wqery6-light.webp
    skip_dirs: []
# ARTICLE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

effects: 
  particles: true
  cursoreffects: true


# COMMENT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
comment:
  enable: false
  system: waline
  config:
    waline:
      serverUrl:
      lang: en-US
      emoji: []
      recaptchaV3Key:
      turnstileKey:
      reaction: false
    gitalk:
      clientID:
      clientSecret:
      repo:
      owner:
      proxy:
    twikoo:
      version: 1.6.10
      server_url:
      region:
    giscus:
      repo:
      repo_id:
      category:
      category_id:
      mapping: pathname
      strict: 0
      reactions_enabled: 1
      emit_metadata: 0
      lang: en
      input_position: bottom
      loading: lazy
# COMMENT <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# FOOTER >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
footer:
  runtime: true
  icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #f54545"></i>'
  start: 2026/01/01 00:00:00
  statistics: true
  customize: "Media about anime and manga for otaku from all over the world!"
  icp:
    enable: false
# FOOTER <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# INJECT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
inject:
  enable: false
  head: 
    -
    -
  footer:
    -
    -
# INJECT <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# PLUGINS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
plugins:
  feed:
    enable: false
  aplayer:
    enable: false
    type: fixed
    audios:
      - name:
        artist:
        url:
        cover:
        lrc:
  mermaid:
    enable: false
    version: "11.4.1"
# PLUGINS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# PAGE TEMPLATES >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
page_templates:
  friends_column: 3
  tags_style: blur
# PAGE TEMPLATES <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# CDN >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
cdn:
  enable: false
  provider: npmmirror
  custom_url: 
# CDN <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

developer:
  enable: false
